### ISSUE TITLE
Display file/path name and line numbers?

### ISSUE THREAD

**Issue by jeetsukumaran** [Olical/vim-enmasse#24]
Is it possible to have the file/path name and line number of the line under the cursor display? This is really quite crucial when editing lines that occur in many files and you want to change only some of them. Otherwise, might as well as ``bufdo``!

**Comment by Olical** [comment]
Closing this since I feel like it's just been left open for too long and will remain that way. Thank you for the interesting discussion though. Maybe it'll be used again some day.'
