### ISSUE TITLE
select more than one line in visual mode

### ISSUE THREAD

**Issue by stoeffel** [Olical/vim-enmasse#28]
Am I doing something wrong or is selecting of more than one line in visual mode not working?
![visual-enmasse](https://cloud.githubusercontent.com/assets/1217681/12972221/943ec8ea-d0a3-11e5-916d-3a37dd23f903.gif)

Btw. this plugin is awesome!

**Comment by Olical** [comment]
Yep, I noticed it was broken a while ago. I can take a look but I think
it's to do with the echo I call every time you move the cursor, maybe?

**Comment by stoeffel** [comment]
Thanks for response. Would be great if you find a solution. I will have a look this weekend as well.

**Comment by Olical** [comment]
It appears to be this https://github.com/Olical/vim-enmasse/blob/74bd2abc3e15faa7d9c721ed6ce5d9a507d79713/autoload/enmasse.vim#L35

If it's replaced with just `echomsg a:msg` (removing the exe, string and new line) it works but fails a test to do with truncation of messages. I also think it pollutes the message buffer then. I'm at work but I can take a look soon :)

**Comment by stoeffel** [comment]
Cool, that was quickly found. No need to hurry to fix it. The plugin is awesome even without that :-)

**Comment by Olical** [comment]
Well I'll get around to it soon anyway. Easy enough fix, it just made one
test fail for some reason. I'm glad you like it! Just saw your post you
linked from too, really good points. I may well uninstall multiple cursors
from my dotfiles, it causes some really weird bugs sometimes that requires
a Vim reboot.
