### ISSUE TITLE
location list support

### ISSUE THREAD

**Issue by DanielFGray** [Olical/vim-enmasse#30]
Syntastic loads errors into the location list, it would be awesome to edit those errors 'EnMasse'. Unless I'm missing something or mis-understand this plugin, it only works with the quick list window.

Would it be possible to get this working with the location list?

**Comment by Olical** [comment]
Hm, I suppose it should be possible. I don't know if location list is
identical to quickfix list, there's some cool setting for quickfix that I
rely on. I don't see why not but I haven't looked into it.

If not, you may be able to migrate location list to quickfix. I thought
there was a way to get syntastic errors in quickfix anyway?

**Comment by dylanfprice** [comment]
I don't think it's possible to get syntastic to populate the quickfix list: https://github.com/scrooloose/syntastic/issues/43. There may be a way to copy contents of the location list into the quickfix list but I haven't figured it out yet.

**Comment by dylanfprice** [comment]
Is this closed as wont fix? Might be worth labeling it as such or something.

**Comment by Olical** [comment]
Ah, sorry about the sudden close. I think it's a wont fix, I think the best way is to copy the location list to the quickfix list somehow. I wasn't planning on supporting both, I hope this isn't too inconvenient.

**Comment by dylanfprice** [comment]
Yeah no worries. I did find https://github.com/stefandtw/quickfix-reflector.vim which makes both quickfix and location list editable, but it doesn't pull out the line contents for lint errors like EnMasse does.
